# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api_pb2 as api__pb2


class ApiStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallApi = channel.unary_unary(
                '/Api/CallApi',
                request_serializer=api__pb2.ApiRequest.SerializeToString,
                response_deserializer=api__pb2.ApiResponse.FromString,
                )


class ApiServicer(object):
    """The greeting service definition.
    """

    def CallApi(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallApi': grpc.unary_unary_rpc_method_handler(
                    servicer.CallApi,
                    request_deserializer=api__pb2.ApiRequest.FromString,
                    response_serializer=api__pb2.ApiResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Api', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Api(object):
    """The greeting service definition.
    """

    @staticmethod
    def CallApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Api/CallApi',
            api__pb2.ApiRequest.SerializeToString,
            api__pb2.ApiResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
