# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import train_pb2 as train__pb2


class TrainStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallTrain = channel.unary_unary(
                '/Train/CallTrain',
                request_serializer=train__pb2.TrainRequest.SerializeToString,
                response_deserializer=train__pb2.TrainResponse.FromString,
                )


class TrainServicer(object):
    """The greeting service definition.
    """

    def CallTrain(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallTrain': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTrain,
                    request_deserializer=train__pb2.TrainRequest.FromString,
                    response_serializer=train__pb2.TrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Train', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Train(object):
    """The greeting service definition.
    """

    @staticmethod
    def CallTrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Train/CallTrain',
            train__pb2.TrainRequest.SerializeToString,
            train__pb2.TrainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
