# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arbiter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='arbiter.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rarbiter.proto\"\x1d\n\x0e\x41rbiterRequest\x12\x0b\n\x03req\x18\x01 \x01(\t\"\x1e\n\x0f\x41rbiterResponse\x12\x0b\n\x03res\x18\x01 \x01(\t2=\n\x07\x41rbiter\x12\x32\n\x0b\x43\x61llArbiter\x12\x0f.ArbiterRequest\x1a\x10.ArbiterResponse\"\x00\x62\x06proto3'
)




_ARBITERREQUEST = _descriptor.Descriptor(
  name='ArbiterRequest',
  full_name='ArbiterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req', full_name='ArbiterRequest.req', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=46,
)


_ARBITERRESPONSE = _descriptor.Descriptor(
  name='ArbiterResponse',
  full_name='ArbiterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='ArbiterResponse.res', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['ArbiterRequest'] = _ARBITERREQUEST
DESCRIPTOR.message_types_by_name['ArbiterResponse'] = _ARBITERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArbiterRequest = _reflection.GeneratedProtocolMessageType('ArbiterRequest', (_message.Message,), {
  'DESCRIPTOR' : _ARBITERREQUEST,
  '__module__' : 'arbiter_pb2'
  # @@protoc_insertion_point(class_scope:ArbiterRequest)
  })
_sym_db.RegisterMessage(ArbiterRequest)

ArbiterResponse = _reflection.GeneratedProtocolMessageType('ArbiterResponse', (_message.Message,), {
  'DESCRIPTOR' : _ARBITERRESPONSE,
  '__module__' : 'arbiter_pb2'
  # @@protoc_insertion_point(class_scope:ArbiterResponse)
  })
_sym_db.RegisterMessage(ArbiterResponse)



_ARBITER = _descriptor.ServiceDescriptor(
  name='Arbiter',
  full_name='Arbiter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=80,
  serialized_end=141,
  methods=[
  _descriptor.MethodDescriptor(
    name='CallArbiter',
    full_name='Arbiter.CallArbiter',
    index=0,
    containing_service=None,
    input_type=_ARBITERREQUEST,
    output_type=_ARBITERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARBITER)

DESCRIPTOR.services_by_name['Arbiter'] = _ARBITER

# @@protoc_insertion_point(module_scope)
