# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import arbiter_pb2 as arbiter__pb2


class ArbiterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallArbiter = channel.unary_unary(
                '/Arbiter/CallArbiter',
                request_serializer=arbiter__pb2.ArbiterRequest.SerializeToString,
                response_deserializer=arbiter__pb2.ArbiterResponse.FromString,
                )


class ArbiterServicer(object):
    """The greeting service definition.
    """

    def CallArbiter(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArbiterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallArbiter': grpc.unary_unary_rpc_method_handler(
                    servicer.CallArbiter,
                    request_deserializer=arbiter__pb2.ArbiterRequest.FromString,
                    response_serializer=arbiter__pb2.ArbiterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Arbiter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Arbiter(object):
    """The greeting service definition.
    """

    @staticmethod
    def CallArbiter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Arbiter/CallArbiter',
            arbiter__pb2.ArbiterRequest.SerializeToString,
            arbiter__pb2.ArbiterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
